/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChatApp: typeof import('./components/ChatApp.vue')['default']
    ChatLayout: typeof import('./components/ChatLayout.vue')['default']
    ChatList: typeof import('./components/ChatList.vue')['default']
    ChatWindow: typeof import('./components/ChatWindow.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    MessageItem: typeof import('./components/MessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
